spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DB}?useUnicode=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  mail:
    host: ${MAIL_HOST}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

app:
  jwtSecret: ${JWT_SECRET_KEY}
  jwtExpirationMs: ${JWT_EXPIRATION}
  jwtExpirationRememberMeMs: ${JWT_EXPIRATION_REMEMBER_ME}
  createPasswordURL: "http://localhost:8080/api/v1/password/create"
  contentURL: ${CONTENT_URL}
